version: '3.8'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "127.0.0.1:4000:4000"
    restart: always
    environment:
      - PORT=4000
      - NODE_ENV=development
      - MONGO_URI=YOUR_MONGO_URI
      - INTERNAL_API_KEY=changeme
      - JWT_SECRET=changeme
      - ADMIN_PASSWORD=changeme
      - WEBSITE_URL=http://localhost:3000

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "127.0.0.1:3000:3000"
    restart: always
    environment:
      - INTERNAL_BACKEND_URL=http://backend:4000
      - INTERNAL_API_KEY=changeme
